name: "yaml_reader_writer"
description: "A simple command-line application."
version: "1.0.0"

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  yaml: ^3.1.0
  meta: ^1.7.0


dev_dependencies:
  lints: "^1.0.0"
